import archiver from 'archiver';
import { Response } from 'express';
import { Modpack } from '../types/index.js';

export interface ExportOptions {
  format?: 'curseforge' | 'modrinth' | 'direct';
}

/**
 * Streams a generated Minecraft modpack zip archive directly to the HTTP response
 * using the archiver library.
 */
export async function exportModpackZip(modpack: Modpack, res: Response, options: ExportOptions = {}) {
  const archive = archiver('zip', {
    zlib: { level: 9 }, // Maximum compression
  });

  const filename = `${modpack.title.toLowerCase().replace(/[^a-z0-9_-]/g, '_')}_v${modpack.minecraftVersion}.zip`;

  res.setHeader('Content-Type', 'application/zip');
  res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);

  archive.on('error', (err) => {
    console.error('Archiver error:', err);
    if (!res.headersSent) {
      res.status(500).json({ error: 'Failed to generate zip file' });
    }
  });

  archive.pipe(res);

  // 1. CurseForge Manifest Format (manifest.json)
  const curseforgeManifest = {
    minecraft: {
      version: modpack.minecraftVersion,
      modLoaders: [
        {
          id: `${modpack.modLoader}-${modpack.minecraftVersion}`,
          primary: true,
        },
      ],
    },
    manifestType: 'minecraftModpack',
    manifestVersion: 1,
    name: modpack.title,
    version: '1.0.0',
    author: 'Collaborative Modpack Maker',
    files: modpack.mods
      .filter((m) => m.source === 'curseforge' && m.externalModId)
      .map((m) => ({
        projectID: parseInt(m.externalModId, 10) || 0,
        fileID: parseInt(m.versionId || '0', 10) || 0,
        required: true,
      })),
    overrides: 'overrides',
  };

  // 2. Modrinth Format (modrinth.index.json)
  const modrinthIndex = {
    formatVersion: 1,
    game: 'minecraft',
    versionId: '1.0.0',
    name: modpack.title,
    summary: modpack.description || '',
    files: modpack.mods.map((m) => ({
      path: `mods/${m.filename || `${m.slug || m.name}.jar`}`,
      hashes: {},
      downloads: m.downloadUrl ? [m.downloadUrl] : [],
      fileSize: 0,
    })),
    dependencies: {
      minecraft: modpack.minecraftVersion,
      [modpack.modLoader]: '*',
    },
  };

  // 3. Human readable README / mod list
  const readmeContent = `# ${modpack.title}
Minecraft Version: ${modpack.minecraftVersion}
Mod Loader: ${modpack.modLoader}
Total Mods: ${modpack.mods.length}

Generated by Collaborative Minecraft Modpack Maker.

## Installed Mods:
${modpack.mods.map((m, i) => `${i + 1}. **${m.name}** (${m.source}) - ${m.summary || 'No description'}`).join('\n')}
`;

  archive.append(JSON.stringify(curseforgeManifest, null, 2), { name: 'manifest.json' });
  archive.append(JSON.stringify(modrinthIndex, null, 2), { name: 'modrinth.index.json' });
  archive.append(readmeContent, { name: 'README.md' });
  archive.append('', { name: 'overrides/config/.gitkeep' });

  await archive.finalize();
}
